### ISSUE TITLE
Invalid use of email comments

### ISSUE THREAD

**Issue by andypalmer** [ecomba/mobbing#2]
The existing mobbing email solution results in an incorrect form of the generated email.
For example, a group email of `invalid@andypalmer.com` with usernames of `andy` and `antony` leads to the generated email `andy+antony+invalid@andypalmer.com`. Emails to this address will be incorrectly delivered to andy, not invalid

See https://en.wikipedia.org/wiki/Email_address#Sub-addressing

**Comment by ecomba** [comment]
You are right @andypalmer , thanks for seeing this (was prolly to happy hacking away to actually look up the sub-addressing spec ;) ).
